ASP.NET Core uygulamsını dockerize yapamk -2
	dockerfile dosyasının oluşturulması

	Dockerize image oluşturma 
	docker build -t udemyaspcoremvc:v1 .
	diyoruz.

	Dockerize container oluşturma
	run komutunu kullanacağız daha işlevsel olduğu için
	docker run -p 5000:80 udemyaspcoremvc:v1
	containerı ayağa kaldırmak için p parametresini eklememiz
	gerekiyor.5000 portu benim işletim sistemimin portu 80 ise ayağa kalakacak
	container içerisinde çalışanın uygulamamnın portu
	bunu dedikten sonra chrome gel url ye localhost:5000 de projeyi göreceksin
	bir container daha ayağa kaldıralım
	docker run -d -p 5001:80 udemyaspcoremvc:v1 yazıyoruz

	şimdi bir tane daha container oluşturalım ama bu sefer container 
	ad da verelim 
	docker -d --name myaspcontainer -p 5002:80 udemyaspcoremvc:v1
	diyoruz.
	Şimdi containerları silelim
	ilk önce durdurulsunuz 
	docker stop c1b artık localhostt 5000 portumu çalıştıramayacak
	docker ps -a dersem bütün containerları listeler
	docker rm c1b dediğimde containerrlarımı siliyor
	daha kısa yolu ise silmenin 
	docker ps diyelim ilk 
	docker rm f7b --force
	force parametresiyle çalışsa bile proje silebiliyoruz
